"""Fisher-Simplex: canonical simplex geometry via the Fisher amplitude lift."""

__version__ = "0.3.0"

from fisher_simplex.core import (
    binary_fisher_angle,
    binary_overlap,
    effective_number_herfindahl,
    effective_number_shannon,
    fisher_lift,
    fisher_project,
    forced_coordinates,
    forced_pair,
    gini_simpson,
    h3,
    herfindahl,
    overlap_divergence,
    phi,
    psi,
    psi_overlap,
    q_delta,
    qh_ratio,
    shannon_entropy,
    simpson_index,
)
from fisher_simplex.geometry import (
    bhattacharyya_coefficient,
    fisher_barycenter,
    fisher_cosine,
    fisher_distance,
    fisher_expmap,
    fisher_geodesic,
    fisher_kernel,
    fisher_logmap,
    fisher_mean,
    fisher_pca,
    geodesic_interpolate,
    hellinger_distance,
    kernel_matrix,
    pairwise_fisher_distances,
    pairwise_hellinger_distances,
    perturb_simplex,
    sample_near,
    tangent_map,
)
from fisher_simplex.utils import closure, project_to_simplex, validate_simplex

__all__ = [
    "bhattacharyya_coefficient",
    "binary_fisher_angle",
    "binary_overlap",
    "closure",
    "effective_number_herfindahl",
    "effective_number_shannon",
    "fisher_barycenter",
    "fisher_cosine",
    "fisher_distance",
    "fisher_expmap",
    "fisher_geodesic",
    "fisher_kernel",
    "fisher_lift",
    "fisher_logmap",
    "fisher_mean",
    "fisher_pca",
    "fisher_project",
    "forced_coordinates",
    "forced_pair",
    "geodesic_interpolate",
    "gini_simpson",
    "h3",
    "hellinger_distance",
    "herfindahl",
    "kernel_matrix",
    "overlap_divergence",
    "pairwise_fisher_distances",
    "pairwise_hellinger_distances",
    "perturb_simplex",
    "phi",
    "project_to_simplex",
    "psi",
    "psi_overlap",
    "q_delta",
    "qh_ratio",
    "sample_near",
    "shannon_entropy",
    "simpson_index",
    "tangent_map",
    "validate_simplex",
]
